DROP TABLE IF EXISTS BANKUSER;
DROP TABLE IF EXISTS ACCOUNT;
DROP TABLE IF EXISTS TRANSACTION;

DROP SEQUENCE IF EXISTS bankuser_seq;
DROP SEQUENCE IF EXISTS account_seq;
DROP SEQUENCE IF EXISTS transaction_seq;

CREATE SEQUENCE bankuser_seq
  START WITH 1
  INCREMENT BY 1;
  
CREATE SEQUENCE account_seq
  START WITH 1
  INCREMENT BY 1;

CREATE SEQUENCE transaction_seq
  START WITH 1
  INCREMENT BY 1;
  
CREATE TABLE BANKUSER (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(32) NOT NULL,
  name VARCHAR(32) NOT NULL,
  email  VARCHAR(50) NOT NULL,
  password  VARCHAR(250) NOT NULL
);

CREATE TABLE ACCOUNT (
  id INT AUTO_INCREMENT PRIMARY KEY,
  account_no INT NOT NULL,
  user_id INT NOT NULL,
  total_balance DECIMAL NOT NULL,
  FOREIGN KEY(user_id) REFERENCES USER(id)
);

CREATE TABLE TRANSACTION (
  id INT AUTO_INCREMENT PRIMARY KEY,
  account_id INT NOT NULL,
  withdraw_amount DECIMAL NULL,
  deposit_amount DECIMAL NULL,
  balance DECIMAL NOT NULL DEFAULT 0,
  transaction_date DATE NOT NULL,
  transaction_type VARCHAR(10) NOT NULL,
  FOREIGN KEY(account_id) REFERENCES ACCOUNT(id)
);